label.titulo.pagina = Título da página
label.novo = Novo
label.excluir = Excluir
label.editar = Editar
label.acao = A\u00C7\u00C3O
label.id = Id
label.nome = Nome
label.buscar.por = Buscar por
label.escolha = Escolha...
label.pesquisar = Pesquisar
label.sim = Sim
label.nao = N\u00C3O
label.modal.titulo = Confirma\u00E7\u00E3o de exclus\u00E3o
label.modal.corpo = Deseja excluir?

label.agenda = Agenda
label.agendas = Agendas
label.nova.agenda = Nova agenda
label.editar.agenda = Editar agenda
label.periodo.disponivel = Per\u00EDodo dispon\u00EDvel
label.manha = Manh\u00E3
label.tarde = Tarde
label.ambos = Ambos
label.salvar = Salvar
label.limpar.formulario = Limpar formulário

label.compromisso = Compromisso
label.compromissos = Compromissos
label.novo.compromisso = Novo compromisso
label.editar.compromisso = Editar compromisso
label.codigo.funcionario = C\u00F3digo funcion\u00E1rio
label.codigo.agenda = C\u00F3digo agenda
label.data = Data
label.horario = Hor\u00E1rio
label.relatorio = Relat\u00F3rio

label.consulta.relatorio = Consulta de relatório
label.data.inicial = Data inicial
label.data.final = Data final
label.nome.funcionario = Nome funcionário
label.nome.agenda = Nome agenda
label.exportar.excel = Exportar Excel